### ISSUE TITLE
Problem with UTF-8-encoded files

### ISSUE THREAD

**Issue by dyve** [hyde/hyde#241]
If I use special characters in a UTF-8 encoded file (like "Groẞ"), they do not carry well to the generated site. All encoding for files seems fine.

Is this a bug in Hyde or do I need a special setting?

**Comment by jonafato** [comment]
@dyve Do you have a minimal test case that demonstrates the issue?

Note: I realize that it's been nearly two years since this issue was opened, so you've probably forgotten about this by now, but I'd like to address it if possible.

**Comment by dyve** [comment]
@jonafato No, I don't have a test case (as you say, it's been almost 2 years). I haven't used hyde in a while either, do I doubt I'll come across the problem again.

**Comment by Descent098** [comment]
Going to close this issue since there is not enough info to go off. We'll cross this bridge when it pops up again.
