### ISSUE TITLE
Have a way to change "media" dir automatically

### ISSUE THREAD

**Issue by tasn** [hyde/hyde#257]
For caching purposes, it's better if it was possible to change it so the media/ dir won't be copied, but instead copied and renamed from config, to for example media1, or media2, or media-<githash>. This would make it possible to set "expiry" to never on the media dir on the server, resulting in better caching.
This can be achieved by changing media_url, and then just renaming the dir. Would have been nicer to have it automatic.

**Comment by jonafato** [comment]
This appears to be a duplicate of #198, though I'm not entirely sure based on the wording used. @tasn: would a cache invalidation solution that satisfied that issue also address this one? If so, I'd like to close this as a duplicate to keep all discussion and work being done on the feature in one place.

**Comment by tasn** [comment]
Yes, this is a duplicate.
