### ISSUE TITLE
hyde requesting specific version of jinja2

### ISSUE THREAD

**Issue by dcolle** [hyde/hyde#264]
end of last year / beginning of this year, I have built a website with hyde.
Now on a new machine, I tried to regenerte the site with "hyde gen -r", getting the following tracebak:
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/hyde", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <modu\
le>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolv\
e
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Jinja2==2.7.1
I have jinja2 v2.7.3 installed, via portage on gentoo v2.7.1 not available anymore.
To avoid installing older versions manually and possibly interfering with the package system, it would be nice to have a new release of hyde that can cope with newer versions of jinja2. Thanks a lot!
for my curiosity: where is this version requirement specified???
Kind regards,
Didier

**Comment by boghison** [comment]
I have the same issue. @dcolle have you found a fix?

**Comment by moorepants** [comment]
You could use a virtualenv to isolate the website and its dependencies.

Versions are likely specified in the setup.py and/or a requirements.txt

**Comment by llonchj** [comment]
@boghison @dcolle the issue should be fixed now using the master branch of the repository.
Thanks a lot for your help!
