### ISSUE TITLE
Point out specific node with `resource`

### ISSUE THREAD

**Issue by softvar** [hyde/hyde#266]
`resource.node` gives the current node. But I want to list down the content(blogs) from some other folder.
Is there a way to point a particular node but not current node, something like `resource'specific_node'..walk_resources_sorted_by_time()`, `specific_node'? Please help!

**Comment by softvar** [comment]
Oops! It got fixed with `site.content`. Is it the right way?

**Comment by lakshmivyas** [comment]
Yes `site.content` is the starting point for node search.  You can use the functions a) `node_from_path` or b) `node_from_relative_path` to get to a specific folder.

**Comment by softvar** [comment]
Great help! Thanks!
