### ISSUE TITLE
New development?

### ISSUE THREAD

**Issue by mattben** [hyde/hyde#268]
Will there be new development on the hyde project? The documentation has broken links. Has this project been abandoned?

**Comment by hickford** [comment]
Last commit August 2013.

@lakshmivyas?

**Comment by moorepants** [comment]
@llonchj Can you please comment on what is going on? This project seems abandoned but you now have push rights and there is a flurry of activity. What is the project's status?

**Comment by lakshmivyas** [comment]
@moorepants - @llonchj is now a hyde maintainer.  
https://groups.google.com/forum/#!topic/hyde-dev/v06O9axYSGw

**Comment by moorepants** [comment]
Thanks. Sounds good.

**Comment by mattben** [comment]
Thank you!

**Comment by hickford** [comment]
Cool look forward to a new release on PyPI https://pypi.python.org/pypi/hyde
