### ISSUE TITLE
FYI, we built this with Hyde

### ISSUE THREAD

**Issue by salimfadhley** [hyde/hyde#269]
[The Free Python Job Board](http://pythonjobs.github.io/) is built with Hyde. I thought you might enjoy it as an example of a website that's buitl on demand (by a Github Push) in Travis, all hosted for free on Github.io

[Our Project](https://github.com/pythonjobs)

**Comment by lakshmivyas** [comment]
@salimfadhley  - Looks great.  Thanks for sharing. Do you have a blog post somwhere describing your experience?

**Comment by salimfadhley** [comment]
http://mauveweb.co.uk/posts/2015/03/python-jobs-board.html

**Comment by salimfadhley** [comment]
https://salimfadhley.wordpress.com/2015/03/13/advertise-a-new-python-job-by-making-a-github-push/
