### ISSUE TITLE
hyde gen -r corrupts js file on copy

### ISSUE THREAD

**Issue by moorepants** [hyde/hyde#271]
I'm using Bootstrap 2 for a site. I just recently upgraded to the last 2 version: 2.3.2 and now `hyde gen -r` corrupts the `bootstrap.js` file.

To reproduce, add `bootstrap.js` from http://getbootstrap.com/2.3.2/assets/bootstrap.zip to a hyde project and run `hyde gen` then `hyde gen -r`. I get a diff like this:

```
moorepants@moorepants-2170p:moorepants.info(master)$ diff deploy/media/bootstrap/js/bootstrap.js content/media/bootstrap/js/bootstrap.js 
1586c1586
<               && /%24href.position%28%29.top%20%2B%20%28%21%24.isWindow%28self.%24scrollElement.get%280%29%29%20%26%26%20self.%24scrollElement.scrollTop%28%29%29%2C%20href ) || null
---
>               && [[ $href.position().top + (!$.isWindow(self.$scrollElement.get(0)) && self.$scrollElement.scrollTop()), href ]] ) || null
```

It only mess up line 1586 for some reason.

**Comment by lakshmivyas** [comment]
@moorepants - Unless excluded, hyde runs templating on all files.  The recommended approach here is to add a meta.yaml file with `uses_template: false`.

See: https://github.com/hyde/hyde/issues/216

**Comment by moorepants** [comment]
Thanks. I added a `meta.yaml` file to the directory with the `js` files and all is well.
