### ISSUE TITLE
Requirements are too restricted

### ISSUE THREAD

**Issue by jd** [hyde/hyde#290]
It's a pain to install Hyde with other software. We should stop doing that.

**Comment by moorepants** [comment]
+1

I saw the argument that hyde is not a library so it should have fixed requirements in another issue and that has some merit, but when you add other software into the build pipeline for a site these restrictions cause conflicts. It shouldn't be too hard to support a range of versions for the dependencies to remedy this.

**Comment by lakshmivyas** [comment]
@jd / @moorepants  -  I chose to restirict the versions after hyde was broken once because of a Jinja issue and once because of smartypants.   I agree that its too restricitive right now.  Since we have more activity and more maintainers, I think its okay for us to relax the requirements a little bit.  Since you both seem to be using hyde as a part of a larger deployment, can you tell me how much the requirements need to be relaxed (a PR maybe?)

Is there a way to test against the entire version range or the latest subset of it using travis?

Thank you.

**Comment by moorepants** [comment]
It is fairly straightforward to setup a matrix on Travis to test against the all the oldest dep versions and the newest dep versions. I often setup three entries: oldest supported dep releases, newest supported dep releases, and head of master on the deps.

**Comment by lakshmivyas** [comment]
@moorepants - Thank you.  Would it work for you if the build version part is wildcarded (x.x.*) in the deps?

**Comment by jonafato** [comment]
I'm interested in hearing how this is being used in these scenarios. I'm a a big proponent of "it's an application, not a library", but perhaps it's both. i.e. it's possible that we can view much of the code in Hyde as a library that can be used by several applications, one of which is Hyde's CLI. Library code should support all sensible versions of dependencies, but my argument for application version locking (the application here being the Hyde CLI) is that the behavior of the installed application should never change even when dependencies are updated. That said, two (technically three) questions:

1. How are you using Hyde within your build pipeline? Is this something that makes sense as a Python import, or is it more suited to an implementation-ignorant executable?

2. Would exposing parts of Hyde as a less restrictive library and keeping the CLI's dependencies locked be an option here? This would theoretically allow users to use `libhyde` (for lack of a better term) within their applications while keeping the versions locked for the more common use case of "I just want something I can run to generate a blog".

**Comment by moorepants** [comment]
I don't use hyde as a library. I setup a conda environment for building a website. A particular website may use hyde and variety of other tools (some python based) to generate all of the content in the website. For example, I may use Sphinx to process some things or I may use IPython. If any of the packages that I need to use in my environment conflict with hyde's exact required versions, then their are issues. I suspect that I could try to isolate hyde and it's deps from my other packages, but that sounds like a pain. I'd really just like to `conda create -n my-website-env sphinx hyde ipython docutils etc etc` and a combination of working dependencies will be found with conda's SAT solver. But very specific hyde dep versions makes this impossible sometimes.

**Comment by jonafato** [comment]
@moorepants I'm not a fan of relaxing the project's requirements for this use case, though I'm open to hearing others' rationale in favor of this approach.

Personally, I create separate virtual environments in cases like this one. Hyde and some of these  are unrelated except for having some common dependencies. Separating them allows each application to specify its own requirements and avoids this conflict. As an added bonus, your `hyde` environment can be locked to a specific version of Hyde and make sure that all of the places you use it have the same behavior. The fact that multiple CLI tools shown here are written in Python is coincidental; they shouldn't need to share any more dependencies than one tool written in Python and another written in Ruby.

**Comment by jd** [comment]
What you do personally is great, but that's not how everybody else works. Especially with for example Linux distributions who are going to ship that. They're not going to be able to satisfy all the dependency is they are too strict. Same problem is for people using pip in their system without venv. Most people don't know and don't want to know how to use venv anyway.

If hyde supports multiple version of a dependency, then it should be able to tell so. That's what this is about. If some versions of its dependencies does not work, then you specify it too. No more, no less. And everybody is happy! :-)

**Comment by lakshmivyas** [comment]
Fixed.
