### ISSUE TITLE
Add CONTRIBUTING.rst

### ISSUE THREAD

**Issue by jonafato** [hyde/hyde#303]
Hyde should have a contributing guide. Minimally, this should include steps required to get a pull request accepted and merged such as adding or updating tests and documentation, writing good commit messages, and using the issue tracker.

**Comment by lakshmivyas** [comment]
@jonafato : :+1: .

Does this look like something we can start with: https://github.com/hyde/commando/blob/master/CONTRIBUTING.rst?

**Comment by jonafato** [comment]
The guide from commando looks great; the only change I'd propose is removing the note about updating versions (not every PR will be its own new release).
