### ISSUE TITLE
RFC: Enable branch protection on master

### ISSUE THREAD

**Issue by jonafato** [hyde/hyde#311]
Branch protection prevents force pushes, deletions, and pushing or merging code that fails CI. There are a couple of downsides that come from this (e.g. simply bumping a version requires a PR and outdated pull requests need to be rebased before being merged to ensure that tests pass), but overall, I think it's a very beneficial thing to enable.

@lakshmivyas, @llonchj: any objections?

**Comment by lakshmivyas** [comment]
@jonafato : :+1:  - no objections.

**Comment by llonchj** [comment]
+1

2016-01-31 18:29 GMT+11:00 Lakshmi <notifications@github.com>:

**Comment by jonafato** [comment]
:+1: Done!
