### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by bauripalash** [hyde/hyde#323]
The last commit is about 2 years old.

**Comment by lakshmivyas** [comment]
@bauripalash - Yeah. I've moved onto other things and @llonchj  and @jonafato have as well, I think.

**Comment by bauripalash** [comment]
So,
I want to work on that project and fork it and start with a new name but similar to hyde so people can identify the project.

(And if you want , you can give me the rights of the projects, that's not Necessary)

First option is ok?

**Comment by lakshmivyas** [comment]
@bauripalash - Hyde is MIT licensed (https://github.com/hyde/hyde/blob/master/LICENSE).  You can fork it as long as you follow the license text. 

Now, why not contribute to this project? Perhaps you can take over as the maintainer?

**Comment by bauripalash** [comment]
Okay, now I've decided.
I will fork this project and it'll continue with new name (but similar to hyde) and if i found something That can be improved or fixed in this original project , I'll send a pull request.
I'll comment the repo link in few days.

**Comment by andrewshadura** [comment]
@bauripalash, but why fork? The name is good enough, the author offers you to continue develop it, why not take this offer? I would, if I had time for it.

**Comment by bauripalash** [comment]
@andrewshadura  I'll try to do so from next year. Because currently I'm studying for my Higher Secondary Exam.

**Comment by Descent098** [comment]
To anyone on this chain, I have just started to update and maintain Hyde going forward. If you are interested in helping keep an eye out for the 0.9.0 release which will contain all the details about hyde moving forward.
