### ISSUE TITLE
I installed hyde, but the commands don't work.

### ISSUE THREAD

**Issue by jeanravenclaw** [hyde/hyde#347]
![image](https://user-images.githubusercontent.com/75297066/122644220-ccc9d180-d11c-11eb-8976-efb2296b9fe5.png)

![image](https://user-images.githubusercontent.com/75297066/122644239-dce1b100-d11c-11eb-8b51-98160d446793.png)

I've installed hyde, but the commands don't work. Did I do something wrong?

**Comment by navilan** [comment]
@jeanravenclaw - You might have better luck if you used WSL.  https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview

**Comment by jeanravenclaw** [comment]
Nevermind, the issue was gone after I added the PATH (I had issues with other packages too).
